version: '3'
services:
  pe_on_flask:
    build:
      context: .
      dockerfile: containers/development/Dockerfile
    volumes:
      - .:/src
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=run.py
    command: /bin/bash -c "cd pe_on_flask && poetry run flask run --debug --host=0.0.0.0"
    networks:
      - my-network
networks:
  my-network:
    external: true
